### ISSUE TITLE
nodeathcamskip error

### ISSUE THREAD

**Issue by Owned67** [jacob404/Pro-Mod-4.0#10]
L 09/30/2015 - 17:12:30: [SM] Native "FakeClientCommand" reported: Client 9 is not connected
L 09/30/2015 - 17:12:30: [SM] Displaying call stack trace for plugin "optional/nodeathcamskip.smx":
L 09/30/2015 - 17:12:30: [SM]   [0]  Line 33, C:\Users\Jacob\Desktop\l4d2dev\promod-future\addons\sourcemod\scripting\nodeathcamskip.sp::RemoveSpamBlock()
L 09/30/2015 - 17:21:14: Error log file session closed.

**Comment by jacob404** [comment]
fixed in latest update
