### ISSUE TITLE
Issue with weapon limit

### ISSUE THREAD

**Issue by jbzdarkid** [jacob404/Pro-Mod-4.0#4]
If you have no primary weapon, and try to pick up a weapon that is limited, no warning message appears. This could be potentially confusing.

**Comment by jacob404** [comment]
Since I forgot to fix this I'm reopening it until it is fixed.

**Comment by jbzdarkid** [comment]
So much trust invalidated ._.

**Comment by jacob404** [comment]
To be fair it's practically done I just forgot to finish and ship it. My bad.

**Comment by jacob404** [comment]
Added to private bug / feature tracker under 4.4 milestone.

**Comment by jbzdarkid** [comment]
Ahem.

**Comment by jbzdarkid** [comment]
Ahem.

**Comment by jacob404** [comment]
priorities and time constraints

**Comment by jbzdarkid** [comment]
Hire more promod devs.
