### ISSUE TITLE
Spechud breaks with bad names

### ISSUE THREAD

**Issue by jbzdarkid** [jacob404/Pro-Mod-4.0#7]
![screen shot 2015-01-07 at 10 15 49 pm](https://cloud.githubusercontent.com/assets/5459085/5657318/3a0f28d8-96bb-11e4-8275-31182cecb357.png)

buying a panda (っ◕‿◕)っ✯

**Comment by jbzdarkid** [comment]
Another user in game had the same issue, I believe it may be a mac font problem.

**Comment by jacob404** [comment]
Next time you see this happen can you ask other players if they have the same problem, and if they do, if they are on mac?
