### ISSUE TITLE
where is the source of plugins please?

### ISSUE THREAD

**Issue by Owned67** [jacob404/Pro-Mod-4.0#8]
Hello,

where is the source of plugins please?

for:
Auto Communicator
Charger Chest Bump Fix
L4D2 Undo Friendly Fire Confogl Edition
Add Text To Readyup Panel

Best regards,

**Comment by jbzdarkid** [comment]
https://github.com/jbzdarkid/ProModSource

**Comment by Owned67** [comment]
thanks

**Comment by Owned67** [comment]
thanks, but sorry, all plugin is not here

**Comment by jbzdarkid** [comment]
Okay, it's from a bit of an older version. Which .smx files are missing?

**Comment by Owned67** [comment]
Auto Communicator

**Comment by jbzdarkid** [comment]
What's the actual filename?

**Comment by Owned67** [comment]
autocommunicator.smx

**Comment by jacob404** [comment]
AC is very sloppy on the back end. I'm making some much needed updates and releasing the source with 4.3 in a couple weeks. If you really need the source before then reopen this and let me know.

**Comment by Owned67** [comment]
Hello, i can wait, no worrie.

L4D2 Ready-Up 8.3 missing (obsolete version 8.1 in PromodSource):
L 04/16/2015 - 23:09:47: Info (map "c2m1_highway") (file "errors_20150416.log")
L 04/16/2015 - 23:09:47: [SM] Native "GetClientAuthString" reported: Client 12 is not connected
L 04/16/2015 - 23:09:47: [SM] Displaying call stack trace for plugin "optional/readyup.smx":
L 04/16/2015 - 23:09:47: [SM]   [0]  Line 218, C:\Users\Jacob\Desktop\l4d2dev\myplugins\modified\readyup.sp::IsClientCaster()
L 04/16/2015 - 23:09:47: [SM]   [1]  Line 205, C:\Users\Jacob\Desktop\l4d2dev\myplugins\modified\readyup.sp::Native_IsClientCaster()
L 04/16/2015 - 23:09:47: [SM] Native "IsClientCaster" reported: Error encountered while processing a dynamic native

**Comment by Owned67** [comment]
Hello

4.3 is out but no source found? Forgot?

**Comment by jacob404** [comment]
No, 4.3 was more of a stalling update since people kept poking me to release something. I was planning on putting out the source with 4.4 but I might just do it this weekend instead.

**Comment by Owned67** [comment]
Ok thanks, wait & see :)

**Comment by Owned67** [comment]
Can you upload all source please...... 4.4 is out.

Cheers.

**Comment by jacob404** [comment]
https://github.com/jacob404/myplugins

everything missing should be there now, let me know if you can't find something

**Comment by Owned67** [comment]
Thanks, i don't see your update ^^

List of missing .sp for me:
swamp_finale_fix.sp
tankdoorfix.sp
teamflip.sp
temphealthfix.sp
unified_dist.sp
waterslowdownduringtank.sp
autocommunicator.sp
blockheatseekingchargers.sp
boomer_horde_equalizer.sp
bossspawningfix.sp
bridge_escape_fix.sp
charger_chestbump_fix.sp
clip_removal.sp
despawn_health.sp
eq2_scoremod.sp
finale_tank_blocker.sp
ghost_hurt.sp
infected_flow_warp.sp
l4d_equalise_alarm_cars.sp
l4d_inaudible_ghosts.sp
l4d_mapbased_cvars.sp
l4d_no_cans.sp
l4d_notank.sp
l4d_pounceprotect.sp
l4d_si_slowdown.sp
l4d_tank_hittable_refill.sp
l4d_tank_props.sp
l4d_tankpunchstuckfix.sp
l4d_weapon_attributes.sp
l4d_weapon_limits.sp
l4d2_antibaiter.sp
l4d2_blind_infected.sp
l4d2_character_fix.sp
l4d2_director_commonlimit_block.sp
l4d2_dominatorscontrol.sp
l4d2_drop_secondary.sp
l4d2_godframes_control.sp
l4d2_hittable_control.sp
l4d2_jockey_skeet.sp
l4d2_jockeyed_charger_fix.sp
l4d2_ladderblock.sp
l4d2_meleecontrol.sp
l4d2_no_hunter_deadstops.sp
l4d2_nosecondchances.sp
l4d2_nospitterduringtank.sp
l4d2_notankautoaim.sp
l4d2_si_ffblock.sp
l4d2_slowdown_control.sp
l4d2_spitblock.sp
l4d2_startercommon.sp
l4d2_survivor_ff.sp
l4d2_tank_announce.sp
l4d2_tank_attack_control.sp
l4d2_temphealthmedkits.sp
l4d2_uncommon_blocker.sp
l4d2_uniform_spit.sp
l4d2_weaponrules.sp
l4d2_witch_crown_fix.sp
l4d2_witch_restore.sp
lerpmonitor.sp
musical_jockeys.sp
noboom_nohorde.sp
nodeathcamskip.sp
nosaferoomkits.sp
pause.sp
ratemonitor.sp
rock_stumble_block.sp
scoremod2.sp
si_class_announce.sp
si_fire_immunity.sp
smart_ai_rock.sp
spawnstatefix.sp
stagger_solver.sp
staggerblock.sp
staggersolver.sp

Cheers,

**Comment by jacob404** [comment]
https://github.com/Attano/L4D2-Competitive-Framework/tree/master/addons/sourcemod/scripting

**Comment by Owned67** [comment]
thanks,

and confoglcompmod.sp (all modules) use in promod 4.4?

not found:
bridge_escape_fix.sp
charger_chestbump_fix.sp
clip_removal.sp
despawn_health.sp
eq2_scoremod.sp
ghost_hurt.sp
l4d_si_slowdown.sp
l4d_tank_hittable_refill.sp
l4d2_dominatorscontrol.sp
l4d2_drop_secondary.sp 2.0.2 (i have found 2.0.1 only)
l4d2_spitblock.sp
l4d2_startercommon.sp
l4d2_temphealthmedkits.sp
nodeathcamskip.sp
spawnstatefix.sp
staggerblock.sp
staggersolver.sp

**Comment by jacob404** [comment]
https://github.com/jacob404/myplugins

https://github.com/Attano/Equilibrium/tree/master/addons/sourcemod/scripting

https://github.com/jbzdarkid/ProModSource

**Comment by Owned67** [comment]
Thanks.

and for latest confoglcompmod?  it's 2.2.3 or?

**Comment by Owned67** [comment]
where is source for molotov duration please? i can't found...

**Comment by jacob404** [comment]
https://github.com/jacob404/myplugins/blob/master/si_fire_immunity.sp

**Comment by Owned67** [comment]
Thanks but i get a error:
./compile.sh si_fire_immunity.sp
Compiling si_fire_immunity.sp...SourcePawn Compiler 1.6.0-dev+4171
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC

si_fire_immunity.sp(7) : error 010: invalid function or declaration
si_fire_immunity.sp(9) : error 010: invalid function or declaration
si_fire_immunity.sp(10) : error 021: symbol already defined: "inWait"
si_fire_immunity.sp(11) : error 010: invalid function or declaration
si_fire_immunity.sp(50) : error 029: invalid expression, assumed zero
si_fire_immunity.sp(50 -- 51) : warning 215: expression has no effect
si_fire_immunity.sp(51) : error 001: expected token: ";", but found "if"
si_fire_immunity.sp(51) : warning 217: loose indentation
si_fire_immunity.sp(52) : error 029: invalid expression, assumed zero
si_fire_immunity.sp(53) : error 001: expected token: ";", but found "if"
si_fire_immunity.sp(54) : error 029: invalid expression, assumed zero
si_fire_immunity.sp(54) : warning 217: loose indentation
si_fire_immunity.sp(54) : error 029: invalid expression, assumed zero
si_fire_immunity.sp(54) : error 029: invalid expression, assumed zero
si_fire_immunity.sp(54) : fatal error 127: too many error messages on one line

Compilation aborted.
12 Errors.

**Comment by jacob404** [comment]
yea there's something wrong with the merge it appears. there are random strings all over it '18f71975d6102a463ddfd58724b4420350944267' I'll fix it and reupload in the morning.

**Comment by Owned67** [comment]
same for  ./compile.sh charger_chestbump_fix.sp
Compiling charger_chestbump_fix.sp...SourcePawn Compiler 1.6.0-dev+4171
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC
charger_chestbump_fix.sp(163) : warning 217: loose indentation
charger_chestbump_fix.sp(163) : error 029: invalid expression, assumed zero
charger_chestbump_fix.sp(163 -- 164) : warning 215: expression has no effect
charger_chestbump_fix.sp(164) : error 001: expected token: ";", but found "return"
charger_chestbump_fix.sp(164) : warning 217: loose indentation
charger_chestbump_fix.sp(164) : error 017: undefined symbol "pTarget"
charger_chestbump_fix.sp(164) : fatal error 127: too many error messages on one line

capper_removal.sp:
capper_removal.sp(60) : warning 205: redundant code: constant expression is zero
capper_removal.sp(74) : warning 205: redundant code: constant expression is zero

**Comment by Owned67** [comment]
where is source for molotov duration please? (not in si_fire_immunity.sp)

for increase duration delay, thanks

**Comment by jacob404** [comment]
what are u talking about?

**Comment by Owned67** [comment]
when the Molotov launched by a survivor, it only lasts a second (not even) and I would like to increase the value or leave default

**Comment by jacob404** [comment]
that's a cvar not a plugin, i don't remember what it is though so you'd have to look through confogl.cfg

**Comment by Owned67** [comment]
I have look but not found?!?

**Comment by jacob404** [comment]
lifetime
